@startuml
class CreatePostModel {
    + CreatePostModel(postRepository:IPostRepository, subredditRepository:ISubredditRepository)
    + Title : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + SubredditId : int <<get>> <<set>>
    + OnGet() : void
    + OnPost() : IActionResult
}
PageModel <|-- CreatePostModel
CreatePostModel --> "_postRepository" IPostRepository
CreatePostModel --> "_subredditRepository" ISubredditRepository
CreatePostModel --> "SubredditSelectList" SelectList
@enduml
