@startuml
class EditPostModel {
    + EditPostModel(postRepository:IPostRepository)
    + Id : int <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Content : string <<get>> <<set>>
    + OnGet(id:int) : void
    + OnPost() : IActionResult
}
PageModel <|-- EditPostModel
EditPostModel --> "_postRepository" IPostRepository
@enduml
