@startuml
class IndexModel {
    + IndexModel(subredditRepository:ISubredditRepository, postRepository:IPostRepository)
    + OnGet() : void
}
class "List`1"<T> {
}
PageModel <|-- IndexModel
IndexModel --> "_subredditRepository" ISubredditRepository
IndexModel --> "_postRepository" IPostRepository
IndexModel --> "Subreddits<Subreddit>" "List`1"
@enduml
