@startuml
class PostsModel {
    + PostsModel(postRepository:IPostRepository)
    + OnGet() : void
}
class "List`1"<T> {
}
PageModel <|-- PostsModel
PostsModel --> "_postRepository" IPostRepository
PostsModel --> "Posts<Post>" "List`1"
@enduml
