@startuml
class SubredditModel {
    + SubredditModel(subredditRepository:ISubredditRepository, postRepository:IPostRepository)
    + SubredditName : string <<get>> <<set>>
    + OnGet(subredditId:int) : void
}
class "List`1"<T> {
}
PageModel <|-- SubredditModel
SubredditModel --> "_subredditRepository" ISubredditRepository
SubredditModel --> "_postRepository" IPostRepository
SubredditModel --> "Posts<Post>" "List`1"
@enduml
