@startuml
class Subreddit {
    + Subreddit(id:int, name:string, description:string)
    + Id : int <<get>> <<set>>
    + Name : string <<get>>
    + Description : string <<get>>
    + UpdateName(newName:string) : void
    + UpdateDescription(newDescription:string) : void
}
class "List`1"<T> {
}
Subreddit --> "Posts<Post>" "List`1"
@enduml
