@startuml
class User {
    + User(id:int, username:string, password:string, email:string)
    + Id : int <<get>> <<set>>
    + Username : string <<get>>
    + Password : string <<get>>
    + Email : string <<get>>
    + UpdateUsername(newUsername:string) : void
    + UpdatePassword(newPassword:string) : void
    + UpdateEmail(newEmail:string) : void
}
@enduml
